---
title: "My Screech"
author: "Duncan Wadsworth"
date: "October 8, 2014"
output: html_document
---

Rice University holds a yearly elevator pitch competition for graduate student research.  The idea is to pitch your work in 90 seconds in a way that will excite people and draw interest to the research.  I've been encouraged to enter this year and have relectatly done so.  I say reluctantly because I entered in the competition two years ago, and despite a reasonable amount of preparation, got really nervous during the competion and mumbled my way though half of the pitch.  So I suppose that this is my opportunity to redeem myself.  Michele and Dr. Vannucci thought that the microbiome work would be perfectly suited to this sort of thing since it's sexy and easy to sell.  Here is my attempt at this:

#### Title: 10e14 and me

The title is a play on 23andme, the company that provides genetic analysis to individuals who send saliva samples to be sequenced.

> * I'd like to apologize in advance because today, I'll be talking about poop.

> * By now you've probably heard about the microbiome.  It's the idea that our bodies are not just ours, but also have trillions of microbes that live on and inside of our bodies. And science is beginning to understand that our health is fundamentally related to which microbes are present and how well those microbes are functioning.

> * But the science is still in it's infancy.  Papers get published in top tier journals proclaiming: "Diet rapidly and reproducibly alters the human gut microbiome" and "Obesity alters gut microbial ecology".  Of course, this is important and fundamental work, but 

> * Citizen science and crowd-sourced groups such as $\mu$Biome and The American Gut are taking fecal samples from participants, and for a fee, processing and sequencing the samples.  The data is then shared with the donors in much the same way as the 23andme share genetic information.

> * Second Genome, a startup with .... , just entered an undisclosed equity agreement with the Mayo clinic who will provide them with samples.

> * French firm Enterome Biosciences just obtained 10 million Euros of funding to continue


#### Notes:

* From some VC page: "Seres Health, Enterome, Second Genome, Evolve Biosystems, AOBiome are all leading the way in this space."


    